### ISSUE TITLE
创建订单接口处理错误

### ISSUE THREAD

**Issue by HEYAN123** [orangiest/ad-cms-project#16]
材料和工艺传的是数组，创建成功后调用/api/eff/接口，查到的是字符串
![image](https://user-images.githubusercontent.com/37286512/88193894-c1ea9080-cc70-11ea-8b2e-cf594f24756e.png)

**Comment by HEYAN123** [comment]
admin_status: 0
amount: 80
create_time: 1595430127
customer_name: "京东快递"
deadline_time: 1595520000
department: "铁皮部"
discount: 0.8
file_name: "123.jpg"
maker_id: 19
material_id: "[9,7]"     <<-----------------
order_status: 0
origin_amount: 100
process: "["鸽","削"]"   <<----------------
system_id: 7

**Comment by orangiest** [comment]
fixed

**Comment by HEYAN123** [comment]
![image](https://user-images.githubusercontent.com/37286512/88307093-1c055780-cd3e-11ea-9501-62005615c722.png)
请求到的还是字符串

**Comment by orangiest** [comment]
fixed
