### ISSUE TITLE
关于订单中的材料字段

### ISSUE THREAD

**Issue by HEYAN123** [orangiest/ad-cms-project#17]
材料字段只返回了相关id，没返回具体的材料名，订单详情里没有办法显示材料名称，前端不可能根据材料id数组去便利请求获取材料名。
![image](https://user-images.githubusercontent.com/37286512/88196084-5e159700-cc73-11ea-87cb-7b469907b726.png)
所以材料字段需要返回包含id和名称的数组。例如：
[
  {
    id: '12',
    name: '木头'，
  },
]

**Comment by orangiest** [comment]
fixed
