### ISSUE TITLE
下载订单接口download不通

### ISSUE THREAD

**Issue by HEYAN123** [orangiest/ad-cms-project#18]
下载全部情况：
![image](https://user-images.githubusercontent.com/37286512/88200772-30335100-cc79-11ea-81f3-8e80cdd050ae.png)
下载单个情况（是否需要前端怎么处理吗？）：
![image](https://user-images.githubusercontent.com/37286512/88200902-5e189580-cc79-11ea-88ab-93591febd9c6.png)

**Comment by orangiest** [comment]
参考这个 https://juejin.im/post/5c1610cae51d455c627a967e
